### ISSUE TITLE
Found a few problems

### ISSUE THREAD

**Issue by domahoneyii** [matthewwall/weewx-newmountain#1]
Thanks for doing this.  Herb Nyberg, New Mountain CEO, couldn't believe that there was an integration for his weather station.  We plan on deploying a New Mountain weather station in a vineyard in Dartmouth, MA. If you look at this link and scroll down, you will see the weather station above some solar panels - http://internetofthingsagenda.techtarget.com/news/450303343/Tech-accelerator-proves-IoT-projects-in-SMBs-work?utm_medium=EM&asrc=EM_NLS_63881665&utm_campaign=20160906_Wireless%20standard%20smackdown:%20Bluetooth%20vs.%20HaLow_sshea&utm_source=NLS&track=NL-1843&ad=909778&src=909778

1) Missing import sys
2) wimda replaced with parsed in a few places
3) mda replaced with parsed in a few places
4) added Humidity to the output packet
[nm150.py.zip](https://github.com/matthewwall/weewx-nm150/files/462738/nm150.py.zip)

**Comment by matthewwall** [comment]
fixed at commit dda3d36
